### ISSUE TITLE
rename data table filename

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-attune-transect-continuous#2]
provided data table filename: Attune_EDI_table_merged.csv
manually rename in local copy to submit to EDI:
attune-transect-underway-continuous.csv

**Comment by joannekoch** [comment]
Hi @sbeaulieu, is this issue meant for me? If so, it should be assigned to me.

**Comment by joannekoch** [comment]
Attune_EDI_table_merged.csv renamed to attune-transect-underway-continuous.csv.  Replacements made in nes-lter-attune-transect.Rmd.
